### PR TITLE
Fix UI issues on v9.0 [Settings, Search]

### PR DESCRIPTION
**Pull request by theamanjs**
This PR fixes a few UI issues in v9.0
- #1419 
- #1448

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
@theamanjs what's pending for this PR?

**Comment by theamanjs** [comment]
@Gauravjeetsingh I was planning to fix issue #1448 in this PR as well. This is in progress.

**Review by inderpreetsingh — APPROVED** [review]
Looks good!

**Comment by inderpreetsingh** [comment]
Merging this one, needed in #1460

**Pull request merged**
