### PR TITLE
Sdc issues 9.0

### PR DESCRIPTION
**Pull request by theamanjs**
fixes: #1469 
sdc fix

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
@theamanjs When we scroll to a shabad after minimzing the single display tab, and then open the tab, it won't be at the latest scroll. Can you look into that?

**Comment by theamanjs** [comment]
> @theamanjs When we scroll to a shabad after minimzing the single display tab, and then open the tab, it won't be at the latest scroll. Can you look into that?

Veerji, I have just fixed this one right now. Can you please have a look again?

**Comment by theamanjs** [comment]
scroll active verse after maximize sdc

**Comment by Gauravjeetsingh** [comment]
@theamanjs veerji, I think you forgot to push the files? There is no new commit for above change.

**Comment by theamanjs** [comment]
> @theamanjs veerji, I think you forgot to push the files? There is no new commit for above change.

veerji, I have already pushed my changes. Here is the commit hash `be2cae64021d75767d853721519c5f640d3e84f6` you can verify this one.

**Review by Gauravjeetsingh — APPROVED** [review]
LGTM

**Pull request merged**
