### PR TITLE
Add virtual scroll to shabad content

### PR DESCRIPTION
**Pull request by theamanjs**
Add virtual scroll to Shabad pane to load the dom content quickly.

--- 

Without Virtual Scroll:

--- 

With Virtual Scroll:

### CODE REVIEW

**Comment by theamanjs** [comment]
@Gauravjeetsingh veerji, can you please review this one?

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]
Good find @theamanjs !!!
But with this, I think the scroll to active verse has stopped working, can you take a look?


Peek 2022-03-01 14-50

**Comment by theamanjs** [comment]
Oh, I see. I will fix this one.

**Comment by inderpreetsingh** [comment]
I deleted the `9.0-fix` branch after merging. You can open this directly to dev now.

**Pull request closed without merging**
