### PR TITLE
#487 Making quick tools to overlay on the slide

### LINKED ISSUE #487: Quick tools should overlay on top of the slide, not push everything over
quick tools

### PR DESCRIPTION
**Pull request by sukhpalsingh**
Fixes #487 

Making the quick tools to overlay on the slide rather than pushing the slide.

### CODE REVIEW

**Comment by inderpreetsingh** [comment]
Thank you @sukhpalsingh  veerji. This looks good to me code wise, needs to get design input from @saintsoldierx

**Comment by maneetpaul** [comment]
@sukhpalsingh @inderpreetsingh can we make the overlay slightly less transparent? So we can't see the text as clearly that is behind the quick tools

**Comment by sukhpalsingh** [comment]
Made changes to the background opacity and color so that it does not look too transparent as below:

**Comment by tarunsingh5** [comment]
really like this vs the pushing the side in - @saintsoldierx can you give us a quick thumbs up

**Comment by maneetpaul** [comment]
Merging into alpha for QA so we can include in next release. We can adjust if needed.

**Comment by saintsoldierx** [comment]
It looks great - but I preferred it to be most transparent. Can we change the opacity to make it xparent please. Use case is if it is being used in single screen mode and user needs to change the font size, they can do so without disrupting people who are reading too much.

**Comment by maneetpaul** [comment]
> It looks great - but I prefer it to be more transparent. Can we change the opacity to make it xparent please. Use case is if it is being used in single screen mode and user needs to change the font size, they can do so without disrupting people who are reading too much.

We can make it transparent, but let's do an opacity a bit more solid than what it was before? The text from the slide was blending in too much with the tools text. 

Also, our analytics show that single display mode is rarely (if at all) used. So I don't think this will be an issue.

**Pull request merged**
