### PR TITLE
Add Misc slides section inside Announcement overlay

### PR DESCRIPTION
**Pull request by yadvirkaur**
#1913

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
@yadvirkaur Can you also update the UI screenshot here in the PR,.

For reference, link to slack conversation about this UI: https://khalis.slack.com/archives/GFC0Q03M3/p1712838613942029

**Comment by yadvirkaur** [comment]
So for the UI of the Misc slides section inside the Announcement overlay, we came up with different design options to choose from: 
image (5)
image (6)
image (7)
image (8)
image (1)
image (2)
image (3)
image (4)

**Comment by Gauravjeetsingh** [comment]
Thank you @yadvirkaur, the code looks perfect to me.

@saintsoldierx veerji, do you have any final input on the design, this is what we currently selected from the above options
Also, I wasn't sure what would be the heading for these options would be, so we kept it "Add Slides" Should it be labelled as something else?


image
image

**Comment by saintsoldierx** [comment]
I think this is okay but yes, some slight changes:

Display Announcement = **Publish**
Add Slides = **Popular Slides**
Add Dhan Guru = **Ten Guru Slides**

**Review by Gauravjeetsingh — APPROVED** [review]

**Pull request merged**
