### PR TITLE
feat: add google analytics GA4

### PR DESCRIPTION
**Pull request by theamanjs**
- Adds support for Google Analytics GA4; #1677 

Breaking Change:
- `MEASUREMENT_ID=<G-XXXXXXXXX>` and `API_SECRET=<XXXXXXXXXXXX>` variable needs to be added in CI/CD

Additional Information:
- Since GA4 takes around 24-48 hours to show the updated events. I have not removed Universal Analytics. We still have time till 1 July. 

IMPORTANT:
- Do not merge this PR without updating the env file. I will update the PR description once I get the needed data

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
@theamanjs what is needed here? From where can you get the needed data?

**Comment by theamanjs** [comment]
We need measurement id and api secret veerji. I have pinged Prebhdev veerji on slack about that.

**Comment by theamanjs** [comment]
Got the needed information from Prebhdev veerji. I have already added the information on Travis with the help of Inder veerji 🙏 

This PR is also ready now

**Comment by theamanjs** [comment]
Should add GA_ as prefix to env variables first.

**Review by Gauravjeetsingh — APPROVED** [review]

**Pull request merged**
