### PR TITLE
Fix #336 Disable search during database download

### LINKED ISSUE #336: Unable to use app when DB is downloading
When launching the app for the first time, the app is unusable when the DB is downloading.

### PR DESCRIPTION
**Pull request by navdeepsinghkhalsa**

### CODE REVIEW

**Comment by tsingh777** [comment]
I think we need to disable ang search as well when its downloading, both the initial and the update. 
load

**Comment by navdeepsinghkhalsa** [comment]
@tsingh777 I agree. I created an issue for it here: https://github.com/KhalisFoundation/sttm-desktop/issues/344

**Comment by tsingh777** [comment]
I still see issues with the download in this PR.

**Comment by navdeepsinghkhalsa** [comment]
Nothing came up in my testing, Singh Jee. Could you please elaborate?

**Comment by tsingh777** [comment]
While the DB is downloading, and a user enters something into the ang search, the progress bar shifts into the middle of the search bar (the gif above shows this.) Also in this scenario once the DB download is done, the placeholder becomes `undefined` (also in the gif).

if we aren't disabling the ang search in this PR, then it's fine no other issues to report.

**Comment by navdeepsinghkhalsa** [comment]
Achhaa Jee. Thank you. I'll add the fix for #344 to the PR

**Pull request merged**
