### PR TITLE
allows the use of asterisk wild card in first letter search anywhere

### PR DESCRIPTION
**Pull request by inderpreetsingh**
screen shot 2018-09-03 at 8 41 23 pm

### CODE REVIEW

**Comment by tarunsingh5** [comment]
@tsingh777 is this merged?

**Comment by inderpreetsingh** [comment]
@tarunsingh5  @ManjotS  added support to first letter start as well! So when we are using first letter start, we no longer use the optimised query.  🙏

**Comment by tarunsingh5** [comment]
@inderpreetsingh only when there's a wildcard and first letter start right? otherwise we should use optimized

**Comment by inderpreetsingh** [comment]
@tarunsingh5 yes, if it's asterisk - then we use non optimised otherwise optimised.

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa does this need to be closed?

**Comment by navdeepsinghkhalsa** [comment]
@tarunsingh5 @inderpreetsingh Let's put a pin in this. It will have to be written in Realm anyway, which is near merging with dev, so (forgive me) this may be redundant to do in SQLite

**Comment by navdeepsinghkhalsa** [comment]
Closing, as we've moved to Realm

**Pull request closed without merging**
