### PR TITLE
Fix: Ensure consistent logo display across Bani Overlay layouts

### PR DESCRIPTION
**Pull request by yadvirkaur**
#1909

### CODE REVIEW

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]
Looks good, minor change, Can we use the logo we have in split display, attaching the screenshot below.
image

For layouts, in which the logo is outside the content box, use the css filter property to add a subtle drop shadow to it so that it stays visible.

**Comment by Gauravjeetsingh** [comment]
@yadvirkaur The logo is still old one in other layouts
image


Can we use the white transparent logo in every layout, and in top and bottom layouts, adding a shadow to the image, so that it stays visible.

I am thinking of making it something like this
image

**Review by Gauravjeetsingh — CHANGES_REQUESTED** [review]
Need to update logo in all layouts

**Comment by yadvirkaur** [comment]
Yes, will update this. Previously I kept the transparent logo only where it was inside the box.

**Review by Gauravjeetsingh — APPROVED** [review]

**Pull request merged**
