### PR TITLE
Minor Enhancements

### PR DESCRIPTION
**Pull request by Gauravjeetsingh**
Fixes issue #1155 
- Hide the next/prev icon in Sundar gutka bani or ceremony

Fixes issue #1566 
- Make the highlighted text stand out
image
image

Fixes issue #1317 
- Add fade transition in viewer when changing verse (screen recorder didn't catch the smooth effect, its more smoother in actual)
animation

### CODE REVIEW

**Comment by saintsoldierx** [comment]
In regards to the highlighting - I would leave the background transparent unless you can add some left and right padding to each word about 5px. Another option would be is to highlight those words by changing color of the font to some sort of yellow?

**Comment by saintsoldierx** [comment]
Can the fade transition be crossfade rather than blanking to white and fading in every time?

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx veerji, removed the background color from highlighted words. 

Crossfade won't be possible with current setup, because the viewer only has the active verse, which is changed on clicking. We would have to redo that logic to have both previous and active verse in component for crossfade to work.

**Comment by Gauravjeetsingh** [comment]
Merging this for alpha release, will fix the fade animation as discussed on slack in a separate PR

**Pull request merged**
